ALTER TABLE `world_db_version` CHANGE  `required_252_quest_26043` `required_253_searing_gorge` BIT(1); 

UPDATE quest_template SET OfferRewardText='We, too, are suspicious of the Dark Irons.', NextQuestInChain=27963,PrevQuestID=0 , NextQuestID=0 WHERE entry=28582; -- Hero's Call: Searing Gorge!
UPDATE quest_template SET OfferRewardText='We, too, are suspicious of the Dark Irons.', NextQuestInChain=27963,PrevQuestID=0 , NextQuestID=0 WHERE entry=28581; -- Warchief's Command: Searing Gorge!
UPDATE quest_template SET OfferRewardText='Well whadda we have here?  You here to help?', NextQuestInChain=27963 ,PrevQuestID=0 , NextQuestID=0 WHERE entry=28512; -- To the Aid of the Thorium Brotherhood
UPDATE quest_template SET RequestItemsText='Any news?.', OfferRewardText='Let''s see... Overseer Maltorius... we''re quite familiar with him and his work.\n What''s this?  The "archduke"?  That sounds promising.',PrevQuestID=0 , NextQuestID=0, NextQuestInChain=27964 WHERE entry=27963; -- A New Master... But Who?
UPDATE quest_template SET OfferRewardText='Thank you.', PrevQuestID= 0, NextQuestID=0, NextQuestInChain=0 WHERE entry=27960; -- The Fewer, the Better
UPDATE quest_template SET RequestItemsText='You get gears?  How you get them?', OfferRewardText='You didn''t... KILL the machines to get these, right?.\n <Lunk looks upset.>\n Right?', PrevQuestID=0 , NextQuestID=27957, NextQuestInChain=0 WHERE entry=27956; -- Lunk's Task
UPDATE quest_template SET RequestItemsText='If Dinwhisker doesn''t have what we seek, I''m not sure what we''ll do next.', OfferRewardText='A... an ember?  What is this thing?', PrevQuestID=27963 , NextQuestID=0, NextQuestInChain=0 WHERE entry=27964; -- Dig-Boss Dinwhisker
UPDATE quest_template SET OfferRewardText='Do I know you, $R?\r\n\r\n\r\n\r\nSounds like another one of Ragnaros\' minions.  I don\'t like the sound of that.', PrevQuestID=27964 , NextQuestID=0, NextQuestInChain=0 WHERE entry=27965; -- Thorium Point: The Seat of the Brotherhood
UPDATE quest_template SET RequestItemsText='Those poor animals.', OfferRewardText='You''ve got quick hands if you were able to gather this many in such a short time.\n Excellent work, $N.  I''ll make sure these ones don''t go to waste.', PrevQuestID=27960, NextQuestID=0, NextQuestInChain=0 WHERE entry=27961; -- Out of Place
UPDATE quest_template SET RequestItemsText='Bring me the horn, $N.', OfferRewardText='Yup, this was Margol''s horn alright.  No doubt about it.\n Barnabas was a digger, like me.  He never stood a chance in combat against the beast.  I''m glad you were here to set things right.', PrevQuestID=27960 , NextQuestID=0, NextQuestInChain=0 WHERE entry=27962; -- A Lumbering Relic
UPDATE quest_template SET RequestItemsText='', OfferRewardText='No!  You are the same as Thorium Brotherhood dwarf.\n  "Kill dwarf.  Kill spider.  Kill machine.  Kill, kill, kill."\n Lunk come to gorge to go on adventure, not to go on murder spree.\n Goodbye,$R.  You kill too much.', PrevQuestID=27956 , NextQuestID=27958, NextQuestInChain=0 WHERE entry=27957; -- Lunk No Kill
UPDATE quest_template SET RequestItemsText='Well well, you certainly operate quickly!  You do have the venom, right?', OfferRewardText='This... this is way more than I expected.  This will last us for months!', PrevQuestID=27957 , NextQuestID=0, NextQuestInChain=0 WHERE entry=27958; -- A Proper Antivenom
UPDATE quest_template SET RequestItemsText='', OfferRewardText='', PrevQuestID=27957 , NextQuestID=0, NextQuestInChain=0 WHERE entry=27959; -- Lunk's Adventure: Spider Rider
UPDATE quest_template SET RequestItemsText='I won''t fight any elementals until we have proven that they pose a threat to us.', OfferRewardText='It is, unfortunately, as I expected.  These bracers bear the indelible mark of the firelord and his minions./n Very well.  With no Horde or Alliance forces anywhere near this godforsaken gorge, it falls upon the Thorium Brotherhood to stop this Archduke before he spreads any more of his evil.', PrevQuestID=28512 , NextQuestID=0, NextQuestInChain=0 WHERE entry=28099; -- Rasha'krak
UPDATE quest_template SET RequestItemsText='', OfferRewardText='Hello, what is your business in a place like this?/n So Overseer Oilfist sent you? Listen carefully, we have much to discuss in little time.', PrevQuestID=0 , NextQuestID=0, NextQuestInChain=0 WHERE entry=27470; -- A Potential Ally
UPDATE quest_template SET RequestItemsText='', OfferRewardText='Oh, Oilfist sent you?  Hah!/n Did he ever tell you how he got the name Oilfist?  You''ll have to ask him about that one sometime.', PrevQuestID=0 , NextQuestID=0, NextQuestInChain=0 WHERE entry=28514; -- Mouton Flamestar
UPDATE quest_template SET RequestItemsText='', OfferRewardText='Oh, Oilfist sent you?  Hah!/n Did he ever tell you how he got the name Oilfist?  You''ll have to ask him about that one sometime.', PrevQuestID=0 , NextQuestID=0, NextQuestInChain=0 WHERE entry=28515; -- Mouton Flamestar
UPDATE quest_template SET RequestItemsText='', OfferRewardText='There''s no way you coulda killed all the spiders in the gorge, but you definitely made a dent./n Fine, here''s what I promised ya.  Don''t spend it all in one place.  Unless it''s at Thorium Point.', PrevQuestID=0, NextQuestID=0, NextQuestInChain=0 WHERE entry=27980; -- The Spiders Have to Go
UPDATE quest_template SET RequestItemsText='', OfferRewardText='Ye''re a good lad, ye are. I got ye a lil'' present fer yer troubles.', PrevQuestID=0 , NextQuestID=27979, NextQuestInChain=0 WHERE entry=27976; -- Curse These Fat Fingers
UPDATE quest_template SET RequestItemsText='Oilfist says he''s gonna have us makin'' firebombs soon.  All the more need for those flasks.', OfferRewardText='Yeeeeeeowch!  Don''t just go puttin'' this stuff into a dwarf''s open hand.  This stuff is burnin'' up!/n Now me hands are gonna get even more swollen...', PrevQuestID=0 , NextQuestID=27982, NextQuestInChain=0 WHERE entry=27981; -- Heat That Just Don't Quit
UPDATE quest_template SET RequestItemsText='If you''re here for the reward, you''re gonna have to give me the stolen goods.', OfferRewardText='Fantastic work!', PrevQuestID=0 , NextQuestID=0, NextQuestInChain=0 WHERE entry=27977; -- Recon Essentials
UPDATE quest_template SET RequestItemsText='Ye got the thing?', OfferRewardText='<Hansel weighs the stone in his hands.>/n This thing is strange, $N.  I don''t know what to make of it.  It ain''t natural, that''s for sure.', PrevQuestID=27976 , NextQuestID=0, NextQuestInChain=27986 WHERE entry=27979; -- Dark Ministry
UPDATE quest_template SET RequestItemsText='', OfferRewardText='And who might you be?/n Ah, an emissary from the Thorium Brotherhood.  They''re looking for my support?  Fine, I might be willin'' to help out.../n ...for a price.', PrevQuestID=27979 , NextQuestID=0, NextQuestInChain=0 WHERE entry=27986; -- In the Hall of the Mountain-Lord
UPDATE quest_template SET RequestItemsText='A ruby-hilted hammer... it has a nice ring to it.', OfferRewardText='Hmm... the gems looked... sparklier from afar.  Up close, they look kind of dingy./n Ah well!  A little spit and polish should do the trick, and if not, I can use ''em to practice my disenchanting.', PrevQuestID=27981 , NextQuestID=0, NextQuestInChain=0 WHERE entry=27982; -- Twilight Collars
UPDATE quest_template SET RequestItemsText='', OfferRewardText='', PrevQuestID=0 , NextQuestID=0, NextQuestInChain=0 WHERE entry=27983; -- Lunk's Adventure: Cranky Little Dwarfs
UPDATE quest_template SET RequestItemsText='', OfferRewardText='I have accepted my fate here in this cage, but the prayer must be found.', PrevQuestID=0 , NextQuestID=0, NextQuestInChain=27985 WHERE entry=27984; -- Lunthistle's Tale
UPDATE quest_template SET RequestItemsText='', OfferRewardText='', PrevQuestID=27984, NextQuestID=0, NextQuestInChain=0 WHERE entry=27985; -- Prayer to Elune
UPDATE quest_template SET RequestItemsText='', OfferRewardText='If nothin'' else, you bought us some time, and some room to open up our supply lines through this siege./n Yer a fine $C.', PrevQuestID=27986, NextQuestID=0, NextQuestInChain=0 WHERE entry=28028; -- Siege!
UPDATE quest_template SET RequestItemsText='', OfferRewardText='And who might you be?/n Ah, an emissary from the Thorium Brotherhood.  They''re looking for my support?  Fine, I might be willin'' to help out.../n ...for a price.', PrevQuestID=27986, NextQuestID=0, NextQuestInChain=0 WHERE entry=28029; -- Set Them Ablaze!
UPDATE quest_template SET RequestItemsText='A real $C woulda caught the bullets with his teeth.', OfferRewardText='I''ll just divvy these up amongst the guards.  Ye have my thanks.', PrevQuestID=27986, NextQuestID=0, NextQuestInChain=28033 WHERE entry=28030; -- They Build a Better Bullet
UPDATE quest_template SET RequestItemsText='I''m finally getting my hands on those lizard gizzards!', OfferRewardText='Ooh, these are nice.  Now, leave me alone with my gizzards.  I''ve got studying to do!/n <Agnes starts to poke the gizzards with a stick.>/n Yes, very interesting.  Very interesting indeed...', PrevQuestID=27986, NextQuestID=0, NextQuestInChain=0 WHERE entry=28032; -- The Mysteries of the Fire-Gizzard
UPDATE quest_template SET RequestItemsText='', OfferRewardText='Well well well.  Look who come searching for Lunk this time!/n This sounds like case for Lunk''s unique brand of no-kill problem-solve.', PrevQuestID=28030, NextQuestID=0, NextQuestInChain=28034 WHERE entry=28033; -- Deceit
UPDATE quest_template SET RequestItemsText='', OfferRewardText='Did I stutter?  I believe I clearly stated that I... won''t.../n Wow, ye''ve got some good moves there!  I''m impressed!', PrevQuestID=28033 , NextQuestID=0, NextQuestInChain=28035 WHERE entry=28034; -- Lunk's Adventure: Rendan's Weakness
UPDATE quest_template SET RequestItemsText='', OfferRewardText='So, Rendan''s on our side?  About time that oaf came around./n Let''s get moving, then.', PrevQuestID=28034, NextQuestID=0, NextQuestInChain=28052 WHERE entry=28035; -- The Mountain-Lord's Support
UPDATE quest_template SET RequestItemsText='', OfferRewardText='Well, here we are./n I hope you''re ready, $N.', PrevQuestID=28035, NextQuestID=28054, NextQuestInChain=0 WHERE entry=28052; -- Operation: Stir the Cauldron
UPDATE quest_template SET RequestItemsText='', OfferRewardText='You''ve done good.  I don''t like slavery either.', PrevQuestID=28052, NextQuestID=0, NextQuestInChain=0 WHERE entry=28054; -- Slavery is Bad
UPDATE quest_template SET RequestItemsText='', OfferRewardText='Strange how so many slaves cope poorly with freedom.  It''s a shame to have to do what we do, but such are the truths of war./n Now, we must move on to more pressing tasks.', PrevQuestID=28052, NextQuestID=0, NextQuestInChain=0 WHERE entry=28055; -- Sweet, Horrible Freedom
UPDATE quest_template SET RequestItemsText='', OfferRewardText='A fight well-fought, <name>!  I''m beginning to feel the tide turn./n Now, when you''re ready, let''s hit these Dark Irons where it really hurts!', PrevQuestID=28052, NextQuestID=0, NextQuestInChain=28057 WHERE entry=28056; -- Rise, Obsidion
UPDATE quest_template SET RequestItemsText='What?  Pillows?/n What?', OfferRewardText='I see Evonice is up to her old tricks again.  I guess I''ll just... um... hang onto these pillows for a while./n The important part is that you''re here.  We''re going to need your help.', PrevQuestID=28056, NextQuestID=0, NextQuestInChain=28060 WHERE entry=28057; -- Kill 'em With Sleep Deprivation
UPDATE quest_template SET RequestItemsText='', OfferRewardText='Twilight''s Hammer, eh?  I should''ve expected as much.  I''m glad you arrived to help them out when you did./n It looks like, despite all odds, we''ve pressed our offensive to the doorstep of Calcinder''s lair.  It''s now time to finish the job.', PrevQuestID=28057, NextQuestID=0, NextQuestInChain=28062 WHERE entry=28060; -- Twisted Twilight Ties
UPDATE quest_template SET RequestItemsText='', OfferRewardText='', PrevQuestID=28060, NextQuestID=0, NextQuestInChain=28064 WHERE entry=28062; -- From Whence He Came
UPDATE quest_template SET RequestItemsText='', OfferRewardText='', PrevQuestID=28062, NextQuestID=0, NextQuestInChain=0 WHERE entry=28064; -- Welcome to the Brotherhood
UPDATE quest_template SET RequestItemsText='', OfferRewardText='', PrevQuestID=28060, NextQuestID=0, NextQuestInChain=0 WHERE entry=28061; -- Minions of Calcinder
UPDATE quest_template SET RequestItemsText='', OfferRewardText='', PrevQuestID=28062, NextQuestID=0, NextQuestInChain=0 WHERE entry=28053; -- Lunk Like Your Style
UPDATE quest_template SET RequestItemsText='', OfferRewardText='Keep the residue pouring in!', PrevQuestID=28064 , NextQuestID=0, NextQuestInChain=0 WHERE entry=13662; -- Gaining Acceptance
UPDATE quest_template SET RequestItemsText='', OfferRewardText='Keep the residue pouring in!', PrevQuestID=28064, NextQuestID=0, NextQuestInChain=0 WHERE entry=7737; -- Gaining Even More Acceptance